### ISSUE TITLE
does this repository support voice cloning?

### ISSUE THREAD

**Issue by movingright** [deepvk/emospeech#4]

**Comment by dariadiatlova** [comment]
Hey, 

This repository does not support voice cloning as it is the implementation of the EmoSpeech paper, which presents the acoustic model for generating mel-spectrograms by conditioning on the text, speaker id and the emotion label.

However, one could find the proposed ideas helpful for adaptating the code to the voice cloning task. Reach out to us if you are interested in this kind of research and have any questions, we are open to discussion!
